// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatepickerController from "./datepicker_controller.js"
application.register("datepicker", DatepickerController)

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)

import IndexPageController from "./index_page_controller.js"
application.register("index-page", IndexPageController)

import NestedFormController from "./nested_form_controller.js"
application.register("nested-form", NestedFormController)

import RelationSearchController from "./relation_search_controller.js"
application.register("relation-search", RelationSearchController)

import RemoteModalController from "./remote_modal_controller.js"
application.register("remote-modal", RemoteModalController)

import TimepickerController from "./timepicker_controller.js"
application.register("timepicker", TimepickerController)
